version: "3.8"

services:

  frontend:
    container_name: desc_frontend
    hostname: desc_frontend
    build: ./apps/Frontend/
    ports:
      - "3000:3000"
    restart:
      always
    networks:
      - mynet

  backend:
    container_name: desc_backend
    build: ./apps/Backend/
    ports:
      - "4000:4000"
    restart: always
    networks:
      - mynet

  postgresql:
    image: postgres:16.1-alpine3.18
    container_name: postgresql
    hostname: postgresql
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: "postgresUser"
      POSTGRES_USER: "postgresUser"
      POSTGRES_PASSWORD: "postgresPassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./apps/postgresql/Init_Database:/docker-entrypoint-initdb.d
      - ./apps/postgresql/postgresql-data:/var/lib/postgresql/data
      - ./apps/postgresql/postgresql.conf:/etc/postgresql.conf:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresUser -d postgresUser" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - mynet




networks:
  mynet: