#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s
##  - scrape_configs:
##    - job_name: monitoring
##  static_configs:
#  targets:
#    - host.docker.internal
#
#

global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: django-monitor

rule_files:
- "django.rules"

scrape_configs:
- job_name: "django"
  metrics_path: /api/prometheus/metrics
  static_configs:
    - targets: ["DescBackend:4000"]